/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import sun.reflect.generics.reflectiveObjects.NotImplementedException;

import java.io.Closeable;
import java.io.IOException;
import java.util.concurrent.ConcurrentLinkedQueue;

public class BacktraceClient {
    private Backtrace backtrace;

    public BacktraceClient(){
        backtrace = new Backtrace();
    }

    public void send(String message) {
        backtrace.addElement(message);
    }

    public void send(BacktraceReport report ){
        backtrace.addElement(report);
    }

}
