/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

public class Backtrace {
    public boolean someLibraryMethod() {
        return true;
    }

    public void test(){
        System.out.println("Backtrace.io");
    }
}
