/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import sun.reflect.generics.reflectiveObjects.NotImplementedException;

import java.io.Closeable;
import java.io.IOException;
import java.util.concurrent.ConcurrentLinkedQueue;

public class BacktraceClient implements Closeable {
    private Backtrace backtrace;

    public BacktraceClient(){
        backtrace = new Backtrace();
    }
    public boolean someLibraryMethod() {
        return true;
    }

    public void send(String message) {
        backtrace.addElement(message);
    }

    public void send(BacktraceReport report ){
        backtrace.addElement(report);
    }

    @Override
    public void close() throws IOException {
        System.out.println("Closing..");
    }
}
