/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import sun.reflect.generics.reflectiveObjects.NotImplementedException;

import java.util.concurrent.ConcurrentLinkedQueue;

public class BacktraceClient {
    private Backtrace backtrace;

    public BacktraceClient(){
        backtrace = new Backtrace();
    }
    public boolean someLibraryMethod() {
        return true;
    }

    public void test(){
        System.out.println("Backtrace.io");
    }

    public void send(String message) {
        backtrace.addElement(1);
    }


    public void send(Throwable throwable) {
        throw new NotImplementedException();
    }

}
