/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import org.junit.Test;
import static org.junit.Assert.*;

public class BacktraceTest {
    @Test public void testSomeLibraryMethod() {
        BacktraceClient classUnderTest = new BacktraceClient();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
