/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import org.junit.Assert;
import org.junit.Test;

public class BacktraceDataTest {
    private static final String message = "test";

    @Test public void initBacktraceDataUsingException() {
        // GIVEN
        Exception exception = new Exception(message);
        BacktraceReport report = new BacktraceReport(exception);
        // WHEN
        BacktraceData data = new BacktraceData(report);
        // THEN
        Assert.assertNull(report.getMessage());
        Assert.assertTrue(report.getExceptionTypeReport());
        Assert.assertEquals(exception, report.getException());
    }

    @Test public void initReportUsingMessage() {
        // WHEN
        BacktraceReport report = new BacktraceReport(message);
        // THEN
        Assert.assertNull(report.getException());
        Assert.assertEquals(message, report.getMessage());
        Assert.assertFalse(report.getExceptionTypeReport());
    }
}
