/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backtrace.io;

import org.junit.Test;

public class EmptyTest {
    @Test public void testSomeLibraryMethod() {
        // GIVEN

        // WHEN

        // THEN

    }
}
